extends: default

rules:
  line-length: disable
  truthy: enable
  colons: enable
  comments: enable
  indentation: enable
  key-duplicates: enable
  empty-lines: enable
  document-start: enable
  new-line-at-end-of-file: enable
  trailing-spaces: enable
  new-lines: enable

